[package]
name = "build-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.63.0"
cc = "1.0.77"
pkg-config = "0.3.26"
color-eyre = "0.6.2"