[package]
name = "aux-os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
build-helper = {path = "../../helper_crates/build-helper" }
cc = "1.0.77"